name: HandyTranslateMac
options:
  bundleIdPrefix: com.handytranslate
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

packages:
  Shared:
    path: Shared

targets:
  HandyTranslateMac:
    type: application
    platform: macOS
    sources:
      - path: macOS
        excludes:
          - Info.plist
          - "*.entitlements"
    dependencies:
      - package: Shared
    info:
      path: macOS/Info.plist
      properties:
        LSUIElement: true
        NSAccessibilityUsageDescription: "HandyTranslate needs Accessibility access to track cursor position and simulate keyboard shortcuts for text translation."
    entitlements:
      path: macOS/HandyTranslateMac.entitlements
      properties:
        com.apple.security.app-sandbox: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.handytranslate.mac
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: false
      configs:
        debug:
          CODE_SIGN_IDENTITY: "-"
        release:
          CODE_SIGN_IDENTITY: "-"

schemes:
  HandyTranslateMac:
    build:
      targets:
        HandyTranslateMac: all
    run:
      config: Debug
    archive:
      config: Release
